### PR TITLE
[ADD] Devil files support in BinaryData editor utility (#153)

### PR DESCRIPTION
**Pull request by bitlinker**
Hi Guys,

Please review simple improvement for the BinaryData editor utility - added DevilData.sbin support.

BTW, I'm C++ developer and very appreciate the work you are doing for bringing back this great game! I have experience with cross-platform development with MSVC/GCC and CMake, OpenGL, Android, reverse engineering binary protocols a little. Unfortunantly I have not much time to spare on the contribution because of frequent overtime at the work, but I would like to join the project and contribute more if you have some spare tasks to do which are not required to be done very fast.
Sorry for my bad English, it is not my native language :)
Thanks.

### CODE REVIEW

**Comment by bitlinker** [comment]
Looks like the Travis build failed because of some wierd upload timeout...

**Comment by compomega** [comment]
Yes that is the unit test build results being uploaded to cdash.org (http://my.cdash.org/index.php?project=comp_hack). I want it to fail if the tests fail but not if the upload fails. Perhaps that part of the travis script could use some work.

Have you tested that out with some demon data? Does the XML look clean? Does the XML produce and identical file again? Just making sure there is not a lingering bug in objgen.

**Comment by compomega** [comment]
Please add encoding="cp932" to the name in libcomp/schema/binarydata/devildata.xml so the generated XML displays Japanese demon names correctly. I'll merge it after that.

**Comment by bitlinker** [comment]
@compomega, done. The XMLfile is clean and pretty easy to edit, but huge(~90Mb). Binary file produced from XML is exactly same as the original one, objgen is working perfectly. Also, translated devil names are successfully shown in the client: http://prnt.sc/en9ysd.

**Pull request merged**
